//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 05:26:04 PM MST 
//


package parse;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isDate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="justify" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="emptyCharacter" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="truncate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="truncateSide" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="packedNumeric" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="category" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="trim" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "field")
public class Field {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "length")
    protected String length;
    @XmlAttribute(name = "required")
    protected String required;
    @XmlAttribute(name = "isDate")
    protected String isDate;
    @XmlAttribute(name = "justify")
    protected String justify;
    @XmlAttribute(name = "emptyCharacter")
    protected String emptyCharacter;
    @XmlAttribute(name = "truncate")
    protected String truncate;
    @XmlAttribute(name = "truncateSide")
    protected String truncateSide;
    @XmlAttribute(name = "packedNumeric")
    protected String packedNumeric;
    @XmlAttribute(name = "category")
    protected String category;
    @XmlAttribute(name = "trim")
    protected String trim;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequired(String value) {
        this.required = value;
    }

    /**
     * Gets the value of the isDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDate() {
        return isDate;
    }

    /**
     * Sets the value of the isDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDate(String value) {
        this.isDate = value;
    }

    /**
     * Gets the value of the justify property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustify() {
        return justify;
    }

    /**
     * Sets the value of the justify property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustify(String value) {
        this.justify = value;
    }

    /**
     * Gets the value of the emptyCharacter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmptyCharacter() {
        return emptyCharacter;
    }

    /**
     * Sets the value of the emptyCharacter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmptyCharacter(String value) {
        this.emptyCharacter = value;
    }

    /**
     * Gets the value of the truncate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruncate() {
        return truncate;
    }

    /**
     * Sets the value of the truncate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruncate(String value) {
        this.truncate = value;
    }

    /**
     * Gets the value of the truncateSide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTruncateSide() {
        return truncateSide;
    }

    /**
     * Sets the value of the truncateSide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTruncateSide(String value) {
        this.truncateSide = value;
    }

    /**
     * Gets the value of the packedNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackedNumeric() {
        return packedNumeric;
    }

    /**
     * Sets the value of the packedNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackedNumeric(String value) {
        this.packedNumeric = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the trim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrim() {
        return trim;
    }

    /**
     * Sets the value of the trim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrim(String value) {
        this.trim = value;
    }

}
