//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 05:26:04 PM MST 
//


package parse;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identify" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="character" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lineRange" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="firstLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="lastLine" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}section" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="identification" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="packedNumeric" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "identify",
    "lineRange",
    "section"
})
@XmlRootElement(name = "line")
public class Line {

    protected Identify identify;
    protected LineRange lineRange;
    @XmlElement(required = true)
    protected List<Section> section;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "identification", required = true)
    protected String identification;
    @XmlAttribute(name = "packedNumeric")
    protected String packedNumeric;

    /**
     * Gets the value of the identify property.
     * 
     * @return
     *     possible object is
     *     {@link Identify }
     *     
     */
    public Identify getIdentify() {
        return identify;
    }

    /**
     * Sets the value of the identify property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identify }
     *     
     */
    public void setIdentify(Identify value) {
        this.identify = value;
    }

    /**
     * Gets the value of the lineRange property.
     * 
     * @return
     *     possible object is
     *     {@link LineRange }
     *     
     */
    public LineRange getLineRange() {
        return lineRange;
    }

    /**
     * Sets the value of the lineRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineRange }
     *     
     */
    public void setLineRange(LineRange value) {
        this.lineRange = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the section property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Section }
     * 
     * 
     */
    public List<Section> getSection() {
        if (section == null) {
            section = new ArrayList<Section>();
        }
        return this.section;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the identification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentification() {
        return identification;
    }

    /**
     * Sets the value of the identification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentification(String value) {
        this.identification = value;
    }

    /**
     * Gets the value of the packedNumeric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackedNumeric() {
        return packedNumeric;
    }

    /**
     * Sets the value of the packedNumeric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackedNumeric(String value) {
        this.packedNumeric = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="character" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Identify {

        @XmlAttribute(name = "character")
        protected String character;
        @XmlAttribute(name = "position")
        protected String position;

        /**
         * Gets the value of the character property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCharacter() {
            return character;
        }

        /**
         * Sets the value of the character property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCharacter(String value) {
            this.character = value;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPosition(String value) {
            this.position = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="firstLine" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="lastLine" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class LineRange {

        @XmlAttribute(name = "firstLine")
        protected String firstLine;
        @XmlAttribute(name = "lastLine")
        protected String lastLine;

        /**
         * Gets the value of the firstLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstLine() {
            return firstLine;
        }

        /**
         * Sets the value of the firstLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstLine(String value) {
            this.firstLine = value;
        }

        /**
         * Gets the value of the lastLine property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastLine() {
            return lastLine;
        }

        /**
         * Sets the value of the lastLine property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastLine(String value) {
            this.lastLine = value;
        }

    }

}
