//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.14 at 05:26:04 PM MST 
//


package parse;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="startPosition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="delimitation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="escape" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                     &lt;sequence>
 *                       &lt;element name="escapeOpen" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                       &lt;element name="escapeClose" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                     &lt;/sequence>
 *                   &lt;/choice>
 *                   &lt;element name="delimiter" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                   &lt;element name="keyValueSeparator" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}fields"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startPosition",
    "length",
    "dateFormat",
    "delimitation",
    "fields"
})
@XmlRootElement(name = "section")
public class Section {

    @XmlElement(required = true)
    protected String startPosition;
    @XmlElement(required = true)
    protected String length;
    protected String dateFormat;
    @XmlElement(required = true)
    protected Delimitation delimitation;
    @XmlElement(required = true)
    protected Fields fields;
    @XmlAttribute(name = "name", required = true)
    protected String name;

    /**
     * Gets the value of the startPosition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartPosition() {
        return startPosition;
    }

    /**
     * Sets the value of the startPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartPosition(String value) {
        this.startPosition = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLength(String value) {
        this.length = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the delimitation property.
     * 
     * @return
     *     possible object is
     *     {@link Delimitation }
     *     
     */
    public Delimitation getDelimitation() {
        return delimitation;
    }

    /**
     * Sets the value of the delimitation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delimitation }
     *     
     */
    public void setDelimitation(Delimitation value) {
        this.delimitation = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * @return
     *     possible object is
     *     {@link Fields }
     *     
     */
    public Fields getFields() {
        return fields;
    }

    /**
     * Sets the value of the fields property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fields }
     *     
     */
    public void setFields(Fields value) {
        this.fields = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="escape" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *           &lt;sequence>
     *             &lt;element name="escapeOpen" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *             &lt;element name="escapeClose" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *           &lt;/sequence>
     *         &lt;/choice>
     *         &lt;element name="delimiter" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *         &lt;element name="keyValueSeparator" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "escape",
        "escapeOpen",
        "escapeClose",
        "delimiter",
        "keyValueSeparator"
    })
    public static class Delimitation {

        protected Object escape;
        protected Object escapeOpen;
        protected Object escapeClose;
        protected Object delimiter;
        protected Object keyValueSeparator;
        @XmlAttribute(name = "type")
        protected String type;

        /**
         * Gets the value of the escape property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEscape() {
            return escape;
        }

        /**
         * Sets the value of the escape property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEscape(Object value) {
            this.escape = value;
        }

        /**
         * Gets the value of the escapeOpen property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEscapeOpen() {
            return escapeOpen;
        }

        /**
         * Sets the value of the escapeOpen property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEscapeOpen(Object value) {
            this.escapeOpen = value;
        }

        /**
         * Gets the value of the escapeClose property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getEscapeClose() {
            return escapeClose;
        }

        /**
         * Sets the value of the escapeClose property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setEscapeClose(Object value) {
            this.escapeClose = value;
        }

        /**
         * Gets the value of the delimiter property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getDelimiter() {
            return delimiter;
        }

        /**
         * Sets the value of the delimiter property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setDelimiter(Object value) {
            this.delimiter = value;
        }

        /**
         * Gets the value of the keyValueSeparator property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getKeyValueSeparator() {
            return keyValueSeparator;
        }

        /**
         * Sets the value of the keyValueSeparator property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setKeyValueSeparator(Object value) {
            this.keyValueSeparator = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
